services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goffeebean-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/goffeebean
      SPRING_DATASOURCE_USERNAME: goffeebean
      SPRING_DATASOURCE_PASSWORD: cup-of-goffee
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - coffee
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: goffeebean
      POSTGRES_PASSWORD: cup-of-goffee
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goffeebean -d goffeebean"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - coffee
    restart: unless-stopped

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - coffee
    restart: unless-stopped

networks:
  coffee:
    driver: bridge

volumes:
  db:
  ollama:
