spring.application.name=coffee
spring.datasource.url=jdbc:postgresql://localhost:5332/goffeebean
spring.datasource.username=goffeebean
spring.datasource.password=cup-of-goffee
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

ollama.base-url=http://localhost:11434
ollama.model=llama3.2:1b
